### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by jcelerier** [jcelerier/RtMidi17#12]

**Comment by cpyarger** [comment]
a bit of an issue I came across when using the library to build via CI for MacOS 
![image](https://user-images.githubusercontent.com/1778298/85213055-4fac2680-b327-11ea-86a5-1b4f821d12e4.png)

**Comment by cpyarger** [comment]
Side Note, I am finding Azure Pipelines to work amazingly for CI building Mac, Linux  and Windows. Since it has VMs available for all of them, And maybe you can use the obs-websockets CI stuff as a baseline (:

**Comment by jcelerier** [comment]
This issue is due to the JACK version shipped on the VM being too old. Latest versions of JACK have this bug fixed.

**Comment by cpyarger** [comment]
I am installing jack via homebrew as part of install-dependencies-macos.sh in my CI folder

**Comment by cpyarger** [comment]
Found and fixed my issues, Aparently Homebrew doesn't have a more current build of jack, So I installed it via macports

**Comment by jcelerier** [comment]
good to know, thanks !

**Comment by cpyarger** [comment]
Also, If you need a hand setting up CI, Let me know, I currently am building your library as a submodule of my plugin, and have it all working now (: [Plugin](https://github.com/Alzy/obs-midi/releases)
![image](https://user-images.githubusercontent.com/1778298/85280554-58e7e100-b456-11ea-8d17-558b6579f8a4.png)
![image](https://user-images.githubusercontent.com/1778298/85281506-1aebbc80-b458-11ea-8749-e44d64c44c58.png)
The Releases page was automatically generated and the binaries that I had packaged during the main CI builds were attached

**Comment by jcelerier** [comment]
done :-) since it's header only I don't think it's worth to make release assets - I think it's better to clone master.
