### ISSUE TITLE
Help with Xcode library linking

### ISSUE THREAD

**Issue by tsbkelly** [jcelerier/RtMidi17#13]
Hi,

Really sorry to ask for help here, but I'm bashing my head against a brick wall. I'm trying to move from Rtmidi to Rtmidi17, but I can't get Rtmidi17 to compile in Xcode as an external library using angled brackets. If I try replacing all the includes with double-quotes, the linker fails. Any help would be incredibly gratefully received.

Thanks

**Comment by jcelerier** [comment]
Hello,
what you need to do is to include the folder that contains the "rtmidi17" folder (the one with the source files)
Though what would make more sense is to move it in an `include` folder as most header-only libs traditionally do, this way you'll only have to : 

* add path/to/rtmidi17/include to the include path in Xcode
* add the preprocessor define RTMIDI17_HEADER_ONLY=1 

OR 

* add path/to/rtmidi17/include to the include path in Xcode
* compile the .cpp file as part of your projet (easiest), or compile it with CMake and link against it (a bit harder, need to set up link paths and make sure that it uses the same CMake flags than your project).

Then the include paths should look like 

    #include <rtmidi17/message.hpp> 

for instance

**Comment by jcelerier** [comment]
I updated the library that way. Can you please test and report if it works that way for you ?

**Comment by tsbkelly** [comment]
Hi,

Thanks so much for the quick response. I've added the path to the Rtmidi17 directory to "Header Search Paths" in Xcode, and added the preprocessor macro as you suggest - now getting the error "Lexical or preprocessor issue -> rtmidi17/rtmidi17.cpp not found". I've tried adding rtmidi17.cpp to the build target, but it's then throwing similar errors.

Thanks

**Comment by jcelerier** [comment]
Can you show the exact error you have ?

**Comment by tsbkelly** [comment]
So sorry - I've just rebuilt everything from scratch with your new folder structure, and everything is working... Sorry for wasting your time!

**Comment by jcelerier** [comment]
No worries, it's not a waste of time - if other people have this problem they'll stumble on this thread and will see that a from-scratch rebuild can help :-)
