### ISSUE TITLE
Bug on MacOSX midiout, sendmessage (MidiOutCore::sendMessage: could not allocate packet list)

### ISSUE THREAD

**Issue by subatomicglue** [jcelerier/RtMidi17#3]
Inside `coreaudio.hpp`, in the `send_message` method:
```
void send_message(const unsigned char* message, size_t size) override
```

There is
```
Byte* buffer = (Byte*)alloca(nBytes + (sizeof(MIDIPacketList)));
ByteCount listSize = sizeof(buffer);   // <---------    size of the pointer
```

But Shouldn't it be:
```
Byte* buffer = (Byte*)alloca(nBytes + (sizeof(MIDIPacketList)));
ByteCount listSize = nBytes + (sizeof(MIDIPacketList));   // <--- size of the allocated bytes
```

Since from the apple docs:
```
MIDIPacket * MIDIPacketListAdd(MIDIPacketList *pktlist, ByteCount listSize, MIDIPacket *curPacket, MIDITimeStamp time, ByteCount nData, const Byte *data);

listSize:  The size, in bytes, of the packet list.
```

You were passing the size of the pointer, not the size of the allocated bytes

I was getting: `MidiOutCore::sendMessage: could not allocate packet list` when attempting to `send_message` a 2 byte ProgramChange.

So Basically I see that the `MIDIPacketListAdd` there is returning NULL, failing to create a packet, because it thinks there is not enough space (because the `buffer` pointer `sizeof(buffer)` is of course 8 bytes only, and we are setting `MIDIPacketListAdd`'s `listSize` to 8 when we actually have tons of space allocated: `nBytes + (sizeof(MIDIPacketList))` in fact).

**Comment by subatomicglue** [comment]
Here is the change:

Was this:
```
    Byte* buffer = (Byte*)alloca( nBytes + (sizeof(MIDIPacketList)) );
    ByteCount listSize = sizeof(buffer);
    MIDIPacketList* packetList = (MIDIPacketList*)buffer;
    MIDIPacket* packet = MIDIPacketListInit(packetList);
```

Should be this:
```
    const ByteCount listSize = nBytes + (sizeof(MIDIPacketList));
    Byte* buffer = (Byte*)alloca( listSize );
    MIDIPacketList* packetList = (MIDIPacketList*)buffer;
    MIDIPacket* packet = MIDIPacketListInit(packetList);
```

**Comment by subatomicglue** [comment]
With that change, I am now able to run `cmidiin` with a virtual input, and `midiout` connected to that virtual input.

**Comment by jcelerier** [comment]
Hello,
I fixed that exact bug one day ago :) 

https://github.com/jcelerier/RtMidi17/commit/3c2d0a723eb8a4894314d80991c08488ae3c5d1e

**Comment by subatomicglue** [comment]
Ha!  Bad Timing.   Thank you!!!

**Comment by jcelerier** [comment]
thanks for looking into it in any case, this kind of contribution is quite appreciated !
