### ISSUE TITLE
Books / information resources needed

### ISSUE THREAD

**Issue by chromafunk** [jcelerier/RtMidi17#5]
Hi, is there any source of information, like a book or some documentation to get me started on writing a simple program and from there, keep on going ? I have several MIDI protocol books and also know enough C++ to start, but I would like to see some implementation or some resources to ease the learning curve with this library. Thanks !

**Comment by jcelerier** [comment]
Hello, the simplest would be to look at the examples here : https://github.com/jcelerier/RtMidi17/tree/master/tests

**Comment by chromafunk** [comment]
Thanks !
