### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by cpyarger** [jcelerier/RtMidi17#8]
Hi Jean, I am trying to swap from rtmidi in my application, to your RtMidi17 library, Would you happen to have any documentation on how to deal with your message callbacks? I am probably missing something obvious.  I am trying to rebuild the function Handle input `https://github.com/Alzy/obs-midi/blob/rtmidi17/midi-agent.cpp`

**Comment by jcelerier** [comment]
Hello,
to use the callbacks the simplest is through e.g. a lambda-function.

for instance: 

    midi_in yourInput = /* blabla */;
    yourInput.set_callback([] (const rtmidi::message& message) { 
        if(message.is_note_on_or_off()) {
          std::cout << message.bytes[0] << " "
                << message.bytes[1] << " "
                << message.bytes[2] << "\n"; 
        } 
    });

**Comment by jcelerier** [comment]
in your case that would likely be something like 
   
	midiin->set_callback([this] (const auto& message) { HandleInput(message); });

or you can use std::bind but that's less pretty

**Comment by cpyarger** [comment]
Sweet! Thank you so much!!! I have gotten it up and working now! Oh, have
you tested cross-platform and had found it works on Linux yet?
Warmest Regards,


Christopher P. Yarger

Phone: 802-505-7574
Skype: cpyarger

/************************************
Based upon email reliability concerns,
please send an acknowledgment in response to this note.

**Comment by jcelerier** [comment]
> Oh, have you tested cross-platform and had found it works on Linux yet?

I am mainly a Linux user, so I can definitely confirm it works there :-)

**Comment by cpyarger** [comment]
Well, I was able to get the thing working, Any suggestions on dealing with the issues caused by rtmidi enumerating the device name?

**Comment by jcelerier** [comment]
Hello,
what issues are those ?

**Comment by cpyarger** [comment]
Device names change, whenever you plug in different devices or add/remove them. making it rather difficult for me to have a stable config file when the names of the ports can change in the background

**Comment by cpyarger** [comment]
Also, I  really appreciate your helper functions for making messages (:

**Comment by cpyarger** [comment]
![image](https://user-images.githubusercontent.com/1778298/82949090-00b1e200-9f71-11ea-9bcd-27e7bfcc40ca.png)

It seems to be a platform-specific issue,  Windows enumerates based off of port number, not device name like linux does.

**Comment by cpyarger** [comment]
I submitted pull request #10  to fix this issue. 
![image](https://user-images.githubusercontent.com/1778298/83504515-975f3100-a492-11ea-8e16-495d0e4bfd95.png) 

As you can see, Ennumeration is now based on device name, so if you only have one device named X-Touch Compact, it is always enumerated 1, if you have 2 X-Touch Compact, it will number them X-Touch Compact 1 and X-Touch Compact 2

**Comment by jcelerier** [comment]
closing as it's been fixed - thanks again
